[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Fuu <g.for.xyz@gmail.com>"]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.104"
api = { path = "crates/api" }
clap = "4.6.7"
displaydoc = "0.2.7"
heck = "0.5.0"
libc = "0.2.189"
log = { version = "0.4.34", features = ["serde", "std"] }
logger = { path = "crates/logger" }
logger-backend = { path = "crates/logger-backend" }
names = { version = "0.14.0", default-features = false }
oneshot = { version = "0.2.1", features = ["std", "async"] }
rustix = { version = "1.1.5", features = [
    "event",
    "fs",
    "process",
    "stdio",
    "thread",
    "time",
] }
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [
    "macros",
    "net",
    "rt",
    "signal",
    "sync",
    "time",
] }
toml = "1.1.6"
virtio-queue = "0.18.0"
vm-memory = { version = "0.18.0", features = [
    "backend-atomic",
    "backend-mmap",
] }
vm-superio = "0.8.2"
vmm = { path = "crates/vmm" }
vmm-sys-util = "0.15.0"

[package]
name = "dragonball-evolved"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
api.workspace = true
clap = { workspace = true, optional = true }
heck = { workspace = true, optional = true }
logger = { workspace = true, optional = true }
logger-backend = { workspace = true, optional = true }
names = { workspace = true, optional = true }
rustix = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_yaml = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
toml.workspace = true
vmm = { workspace = true, optional = true }
vmm-sys-util = { workspace = true, optional = true }

[features]
default = ["runtime"]
runtime = [
    "dep:clap",
    "clap/env",
    "dep:logger",
    "dep:logger-backend",
    "dep:names",
    "dep:rustix",
    "dep:tokio",
    "dep:vmm",
    "dep:vmm-sys-util",
]
schema = [
    "dep:clap",
    "clap/derive",
    "dep:heck",
    "dep:schemars",
    "dep:serde_yaml",
]

[[bin]]
name = "dragonball-evolved"
path = "src/main.rs"
required-features = ["runtime"]

[[bin]]
name = "schema"
path = "src/bin/schema.rs"
required-features = ["schema"]

[build-dependencies]
anyhow.workspace = true

[profile.release]
strip = "none"
debug = "full"
lto = "fat"
codegen-units = 1
